### PR TITLE
refactor into automatic sendExtendedHandshake() for async handshake response

### PR DESCRIPTION
**Pull request by astro**
see GH issue #8

this should break no interfaces. looks okay?

### CODE REVIEW

**Comment by astro** [comment]
Tests run fine. Travis failed because of zuul.

**Comment by astro** [comment]
Any objections?

**Comment by feross** [comment]
Looks good to me. Is there a good reason for `wire.sendExtendedHandshake()` to be public? If not, can we make it a private method (prefix with `_`)?

**Comment by astro** [comment]
Fair enough.

**Comment by feross** [comment]
Released as 1.5.6.

**Pull request merged**
